# Generated by Django 6.0.4 on 2026-08-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('market', models.CharField(default='Yangon', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('recorded_date', models.DateField()),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='marketPrice.crop')),
            ],
            options={
                'ordering': ['-recorded_date', 'category', 'commodity'],
            },
        ),
        migrations.CreateModel(
            name='HarvestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_prices', to='marketPrice.crop')),
            ],
            options={
                'ordering': ['crop', 'year'],
                'unique_together': {('crop', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Profitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=15)),
                ('yield_tons_per_acre', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit_per_acre', models.DecimalField(decimal_places=2, max_digits=15)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='marketPrice.crop')),
            ],
            options={
                'ordering': ['-profit_per_acre'],
                'unique_together': {('crop', 'year')},
            },
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('yield_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='marketPrice.crop')),
            ],
            options={
                'ordering': ['crop', 'year'],
                'unique_together': {('crop', 'year')},
            },
        ),
    ]
