# Generated by Django 6.0.4 on 2026-08-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPrice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('crop_category', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(max_length=20)),
                ('sown_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('harvested_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('production_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('measurement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_data', to='marketPrice.crop')),
            ],
            options={
                'ordering': ['region', 'year', 'crop_category'],
                'unique_together': {('region', 'crop', 'year')},
            },
        ),
    ]
