# Generated by Django 6.0.4 on 2026-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPrice', '0002_regiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('crop_category', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('sown_acres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harvested_acres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('production_tons', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('measurement_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['region', 'crop_category', 'year'],
            },
        ),
        migrations.DeleteModel(
            name='RegionData',
        ),
    ]
