# Generated by Django 4.2.30 on 2026-07-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('CORN', 'Corn'), ('WHEAT', 'Wheat'), ('SOYBEAN', 'Soybean'), ('RICE', 'Rice'), ('COTTON', 'Cotton'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, help_text="Optional label, e.g. 'Standard Rice Plan'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['crop_type'],
                'unique_together': {('owner', 'crop_type')},
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='reorder_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='cost_per_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='quantity_used',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='unit_cost',
            field=models.IntegerField(blank=True, help_text="Cost per unit at time of use; auto-filled from material's latest purchase if left blank.", null=True),
        ),
        migrations.AlterField(
            model_name='stockalertsetting',
            name='low_stock_threshold_tonnes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='price_per_tonne',
            field=models.IntegerField(blank=True, help_text="Only used for 'Sold' transactions", null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity_tonnes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CropRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit')], default='kg', max_length=10)),
                ('quantity_per_acre', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.croprecipe')),
            ],
            options={
                'ordering': ['category', 'material_name'],
            },
        ),
    ]
