# Generated by Django 4.2.30 on 2026-08-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('stock', '0002_croprecipe_alter_material_reorder_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaterialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_plan', to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropMaterialPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit')], default='kg', max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField(default=0)),
                ('days_after_planting', models.IntegerField(default=0)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.cropmaterialplan')),
            ],
            options={
                'ordering': ['days_after_planting', 'category'],
            },
        ),
        migrations.CreateModel(
            name='DefaultCropRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('CORN', 'Corn'), ('WHEAT', 'Wheat'), ('SOYBEAN', 'Soybean'), ('RICE', 'Rice'), ('COTTON', 'Cotton'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('OTHER', 'Other')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['crop_type'],
            },
        ),
        migrations.CreateModel(
            name='DefaultCropRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit')], default='kg', max_length=10)),
                ('quantity_per_acre', models.IntegerField()),
                ('days_after_planting', models.IntegerField(default=0, help_text='When to apply this, counted from planting date')),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.defaultcroprecipe')),
            ],
            options={
                'ordering': ['days_after_planting', 'category'],
            },
        ),
        migrations.RemoveField(
            model_name='croprecipeitem',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='CropRecipe',
        ),
        migrations.DeleteModel(
            name='CropRecipeItem',
        ),
    ]
