# Generated by Django 4.2.30 on 2026-08-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_cropmaterialplan_cropmaterialplanitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultcroprecipeitem',
            name='default_unit_cost',
            field=models.IntegerField(default=0, help_text='Fallback estimated cost per unit (MMK), used until the farmer has actually purchased this material'),
        ),
        migrations.AlterField(
            model_name='cropmaterialplanitem',
            name='category',
            field=models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('labor', 'Labor'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='cropmaterialplanitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit'), ('tree', 'Tree'), ('person_day', 'Person-Day')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='defaultcroprecipeitem',
            name='category',
            field=models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('labor', 'Labor'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaultcroprecipeitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit'), ('tree', 'Tree'), ('person_day', 'Person-Day')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide/Herbicide'), ('feed', 'Animal Feed'), ('labor', 'Labor'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('bag', 'Bag'), ('packet', 'Packet'), ('unit', 'Unit'), ('tree', 'Tree'), ('person_day', 'Person-Day')], default='kg', max_length=10),
        ),
    ]
