# Generated by Django 4.2.30 on 2026-08-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_defaultcroprecipeitem_default_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmaterialplanitem',
            name='actual_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropmaterialplanitem',
            name='material_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_item', to='stock.materialusage'),
        ),
    ]
