# Generated by Django 6.0.7 on 2026-07-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('CORN', 'Corn'), ('WHEAT', 'Wheat'), ('SOYBEAN', 'Soybean'), ('RICE', 'Rice'), ('COTTON', 'Cotton'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('OTHER', 'Other')], max_length=20)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('HARVESTED', 'Harvested'), ('FAILED', 'Failed')], default='PLANNED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
    ]
