# Generated by Django 4.2.30 on 2026-08-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_savedpost_savedpost_unique_saved_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
