# Generated by Django 4.2.30 on 2026-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_title',
            field=models.CharField(blank=True, help_text="e.g. 'Senior Agronomist' or 'Farmer, Bago Region'", max_length=80),
        ),
    ]
