# Generated by Django 6.0.4 on 2026-07-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_harvest_crop_alter_soilreading_crop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('warning', '⚠️ Warning'), ('watch', '👀 Watch'), ('advisory', '📢 Advisory')], max_length=20)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instruction', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField()),
                ('expires_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-effective_date'],
            },
        ),
    ]
