# Generated by Django 6.0.7 on 2026-07-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('size_acres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('rice', 'Rice'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('coffee', 'Coffee'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('other', 'Other')], default='other', max_length=20)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('area_acres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvesting', 'Harvesting'), ('completed', 'Completed')], default='planted', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='farms.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.farm')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farms.crop')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField(auto_now_add=True)),
                ('moisture_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ph_level', models.DecimalField(decimal_places=2, default=7.0, max_digits=4)),
                ('temperature_celsius', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('nitrogen_ppm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('phosphorus_ppm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('potassium_ppm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_readings', to='farms.crop')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
    ]
