# Generated by Django 6.0.7 on 2026-07-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.crop'),
        ),
        migrations.AlterField(
            model_name='soilreading',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_readings', to='crops.crop'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crops.crop'),
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
