# Generated by Django 6.0.4 on 2026-07-26 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_marketnews_marketprice_pricealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_unit', models.CharField(choices=[('kg', 'Per Kilogram (kg)'), ('tonne', 'Per Tonne (1000 kg)'), ('viss', 'Per Viss (1 viss = 1.63 kg)'), ('pyi', 'Per Pyi (1 pyi = ?)'), ('basket', 'Per Basket')], default='tonne', max_length=20)),
                ('preferred_currency', models.CharField(default='MMK', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
