# Generated by Django 6.0.4 on 2026-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='crops.crop'),
        ),
    ]
